### ISSUE TITLE
Socket closed, when state "Connected"

### ISSUE THREAD

**Issue by GodFuper** [FAForever/java-ice-adapter#59]
The game shows that there is no connection with the player. Ice Debug shows that there is a connection (state = 'Connection'). The logs say that the Socket is closed.
```
2024-11-07 04:04:29.825 DEBUG Error while reading from local FA as peer (probably disconnecting from peer) Hann(375817) (com.faforever.iceadapter.ice.Peer:84)
java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:264)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:714)
	at com.faforever.iceadapter.ice.Peer.faListener(Peer.java:81)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.nio.channels.AsynchronousCloseException: null
	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:564)
	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:718)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:675)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:241)
	... 3 common frames omitted
``` 
Need to handle this error correctly, otherwise it will endlessly try to send data and will constantly receive socket is closed.

https://github.com/FAForever/java-ice-adapter/blob/0173f58aa777457ba7cc1d60ba0d59a191318133/ice-adapter/src/main/java/com/faforever/iceadapter/ice/Peer.java#L79-L86

**Comment by GodFuper** [comment]
[ice-adapter-copy.log](https://github.com/user-attachments/files/17667936/ice-adapter-copy.log)
